name: Deploy Api

on:
  push:
    branches:
      - main__api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: copy file via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: ${{ secrets.API_FOLDER }}
          rm: true
          overwrite: true

      - name: Create secrets files
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.API_DOT_ENV_FILE }}" > ${{ secrets.API_FOLDER }}/.env
            echo "${{ secrets.API_FIREBASE_ADMIN_SDK_JSON }}" | base64 -d > ${{ secrets.API_FOLDER }}/firebase-adminsdk.json
            echo "${{ secrets.API_PLANS_JSON }}" | base64 -d > ${{ secrets.API_FOLDER }}/plans.json

            # transformer un json en base64
            # [Convert]::ToBase64String([IO.File]::ReadAllBytes("plans.json"))

      - name: deploy api
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.API_FOLDER }}
            docker-compose down                 # Arrête les conteneurs existants (si nécessaire)
            docker-compose up -d --build        # Construit et démarre les conteneurs en arrière-plan
